/* Rendering, interaction, and game state. No network requests or external libraries. */
(()=>{'use strict';
const D=window.PUZZLE_DATA,$=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';
const pieces=D.pieces.filter(p=>p.pieceId!=='unknown'),byId=new Map(D.pieces.map(p=>[p.pieceId,p]));
const state={mode:'names',view:'all',started:false,done:false,placed:new Set(),selected:null,startTime:0,elapsed:0,preview:false,order:pieces.map(p=>p.pieceId),zoom:1,pan:{x:0,y:0},aim:null};
let width=1000,height=700,layout=new Map(),world,ghost,aimNode,drag=null,pan=null,pinch=null,pointers=new Map(),lastPointerType='mouse',suppressClick=false,dragPosition=null;
function el(tag,attrs={},text){const e=document.createElementNS(NS,tag);for(const [k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text!==undefined)e.textContent=text;return e;}
function say(message,type=''){ $('feedback').textContent=message;$('feedback').className=type;}
function time(ms){let n=Math.floor(ms/1000);return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;}
function tick(){if(state.started&&!state.done)state.elapsed=performance.now()-state.startTime;$('timer').textContent=time(state.elapsed);}
setInterval(tick,250);
function visibleRegion(r){return state.view==='all'||(state.view==='main'?r==='main':r!=='main');}
function fitRect(region,box){let pad=region.id==='main'?30:12,top=region.id==='main'?42:37;const s=Math.min((box.w-pad*2)/region.width,(box.h-top-12)/region.height);return {...box,s,x:box.x+(box.w-region.width*s)/2,y:box.y+top+(box.h-top-12-region.height*s)/2};}
function calcLayout(){width=$('mapStage').clientWidth;height=$('mapStage').clientHeight;layout=new Map();const mobile=width<540,gap=9,rs=D.regions.filter(r=>visibleRegion(r.id));
 if(state.view==='main'){layout.set('main',fitRect(D.regions[0],{x:12,y:30,w:width-24,h:height-92}));return;}
 let x=12,y=42,w=width-24,h=height-101,cols=state.view==='islands'?(mobile?2:3):2;
 if(state.view==='all'){if(mobile){let mh=h*.51;layout.set('main',fitRect(D.regions[0],{x,y,w,h:mh}));y+=mh+gap;h-=mh+gap;cols=3;}else{let mw=w*.59;layout.set('main',fitRect(D.regions[0],{x,y,w:mw,h}));x+=mw+gap;w-=mw+gap;}}
 const islands=rs.filter(r=>r.id!=='main'),rows=Math.ceil(islands.length/cols),cw=(w-gap*(cols-1))/cols,ch=(h-gap*(rows-1))/rows;
 islands.forEach((r,i)=>layout.set(r.id,fitRect(r,{x:x+(i%cols)*(cw+gap),y:y+Math.floor(i/cols)*(ch+gap),w:cw,h:ch})));
}
function transform(){if(!world)return;world.setAttribute('transform',`translate(${state.pan.x} ${state.pan.y}) scale(${state.zoom})`);$('zoomLevel').textContent=Math.round(state.zoom*100)+'%';drawAim();}
function mapPath(p,part,klass='land'){const l=layout.get(part.region);if(!l)return null;const e=el('path',{d:part.d,transform:`translate(${l.x} ${l.y}) scale(${l.s})`,class:klass,'data-id':p.pieceId,'data-region':part.region});return e;}
function drawMap(){calcLayout();const svg=$('map');svg.setAttribute('viewBox',`0 0 ${width} ${height}`);svg.replaceChildren();world=el('g',{id:'world'});svg.append(world);
 for(const r of D.regions){const l=layout.get(r.id);if(!l)continue;world.append(el('rect',{x:l.x-(l.w-r.width*l.s)/2,y:l.y-(l.h-(r.id==='main'?42:37)-12-r.height*l.s)/2-(r.id==='main'?42:37),width:l.w,height:l.h,rx:12,class:'region-card'}));
 // Card label coordinates use the original box, not the projected origin.
 const bx=l.x-(l.w-r.width*l.s)/2,by=l.y-(l.h-(r.id==='main'?42:37)-12-r.height*l.s)/2-(r.id==='main'?42:37);
 world.append(el('text',{x:bx+11,y:by+17,class:'region-name','font-size':l.w<145?'9':'13',style:`font-size:${l.w<145?9:12}px`},r.name));
 if(l.h>72)world.append(el('text',{x:bx+11,y:by+30,class:'region-relation',style:`font-size:${l.w<145?7:9}px`},r.id==='main'?'北が上':r.relation+' · 別縮尺'));
 }
 for(const p of D.pieces)for(const part of p.parts){const e=mapPath(p,part);if(!e)continue;if(p.pieceId==='unknown')e.classList.add('unknown');world.append(e);}
 world.append(el('g',{id:'labels'}));ghost=el('g',{class:'ghost'});world.append(ghost);aimNode=el('g',{class:'aim'});$('map').append(aimNode);paintMap();transform();
}
function paintMap(){if(!world)return;world.querySelectorAll('.land').forEach(e=>{const p=byId.get(e.dataset.id),show=state.placed.has(p.pieceId)||state.preview;e.classList.toggle('placed',state.placed.has(p.pieceId));e.style.fill=p.pieceId==='unknown'?'#b7c4c5':show?p.color:'';e.replaceChildren();if(show)e.append(el('title',{},p.name));});
 const labels=$('labels');labels.replaceChildren();for(const p of pieces){if(!state.placed.has(p.pieceId)&&!state.preview)continue;if(state.mode==='hints'&&!state.done&&!state.preview)continue;for(const part of p.parts){const l=layout.get(part.region);if(!l)continue;const q=[l.x+part.anchor[0]*l.s,l.y+part.anchor[1]*l.s];const large=(part.bounds[2]-part.bounds[0])*l.s>72;labels.append(el('text',{x:q[0],y:q[1],'text-anchor':'middle','dominant-baseline':'middle',class:'piece-label'},large?p.name:String(p.number)));}}
}
function previewSVG(p){const svg=el('svg',{viewBox:'0 0 100 80','aria-hidden':'true'}),n=p.parts.length,cols=n>1?2:1,rows=Math.ceil(n/cols);p.parts.forEach((part,i)=>{const b=part.bounds,w=b[2]-b[0],h=b[3]-b[1],cw=92/cols,ch=61/rows,s=Math.min((cw-9)/w,(ch-7)/h),x=4+i%cols*cw+(cw-w*s)/2,y=4+Math.floor(i/cols)*ch+(ch-h*s)/2;svg.append(el('path',{d:part.d,fill:p.color,transform:`translate(${x-b[0]*s} ${y-b[1]*s}) scale(${s})`}));});return svg;}
function trayPieces(){return state.order.map(id=>byId.get(id)).filter(p=>!state.placed.has(p.pieceId)).filter(p=>{let f=$('filter').value;return f==='all'||(f==='visible'?p.parts.some(s=>visibleRegion(s.region)):p.category===f);});}
function renderTray(){const tray=$('tray'),scroll=tray.scrollTop;tray.replaceChildren();const ps=trayPieces();for(const p of ps){const b=document.createElement('button');b.className='piece-card'+(state.selected===p.pieceId?' selected':'');b.dataset.id=p.pieceId;b.setAttribute('aria-label',state.mode==='names'?p.name:`ピース ${p.number} を選択してヒントを見る`);b.setAttribute('aria-pressed',String(state.selected===p.pieceId));b.append(previewSVG(p));const label=document.createElement('span');label.textContent=state.mode==='names'?p.name:`No. ${String(p.number).padStart(2,'0')}`;b.append(label);
 b.addEventListener('pointerdown',e=>{if(e.button!==0||state.preview||state.done)return;lastPointerType=e.pointerType;select(p.pieceId,false);if(e.pointerType==='touch'&&!e.target.closest('svg'))return;drag={id:p.pieceId,pointerId:e.pointerId,x:e.clientX,y:e.clientY,moved:false};b.setPointerCapture(e.pointerId);e.preventDefault();});
 b.addEventListener('click',e=>{if(suppressClick){suppressClick=false;return;}if(drag?.moved)return;select(p.pieceId,false);});b.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(p.pieceId,true);}});tray.append(b);}
 if(!ps.length){const d=document.createElement('p');d.className='empty-tray';d.textContent=state.done?'✓ すべてのピースを配置しました':'✓ この表示のピースは配置済みです。地図の表示を切り替えて続けましょう。';tray.append(d);}tray.scrollTop=scroll;$('remaining').textContent=`${41-state.placed.size} ピース`;
}
function select(id,keyboard){if(state.preview||state.done)return;state.selected=id;const p=byId.get(id);$('tray').querySelectorAll('.piece-card').forEach(b=>{b.classList.toggle('selected',b.dataset.id===id);b.setAttribute('aria-pressed',String(b.dataset.id===id));});$('hintName').textContent=p.name;const neighbors=p.neighbors.map(n=>byId.get(n)?.name).filter(Boolean);$('hintBasic').textContent=p.hint+(neighbors.length?' 隣接：'+neighbors.join('、')+'。':' 他の自治体とは陸続きではありません。');$('detailText').textContent=p.detail;$('hintDetail').hidden=true;$('hintToggle').setAttribute('aria-expanded','false');$('hintMore').textContent='産物・歴史のヒントを開く ▾';$('hintSources').replaceChildren();p.sources.forEach((u,i)=>{let a=document.createElement('a');a.href=u;a.target='_blank';a.rel='noopener';a.textContent=`出典 ${i+1} ↗`;$('hintSources').append(a);});$('linkedNote').textContent=p.parts.length>1?'↔ 別枠の付属島も、同じピースとして一緒に配置します。':p.parts[0].polygons>1?'↔ 離れた島・飛び地も、一緒に配置します。':'';$('clearSelection').hidden=false;
 $('quickHint').hidden=false;$('quickName').textContent=p.name;$('quickBasic').textContent=p.hint;$('quickTitle').textContent=p.name;$('quickGeography').textContent=$('hintBasic').textContent;$('quickDetail').textContent=p.detail;
 if(!p.parts.some(s=>visibleRegion(s.region))){say('このピースの地域を表示するには、地図の表示を切り替えてください。');}
 else say(state.started?`${p.name}を選択しました。地図へドラッグ、または置きたい場所をタップ。`:'「ゲーム開始」を押すと配置できます。');
 if(keyboard){$('mapStage').focus();state.aim={x:width/2,y:height/2};drawAim();}
}
function clearSelection(){state.selected=null;state.aim=null;ghost?.replaceChildren();drawAim();$('tray').querySelectorAll('.piece-card').forEach(b=>{b.classList.remove('selected');b.setAttribute('aria-pressed','false');});$('clearSelection').hidden=true;$('quickHint').hidden=true;}
function drawAim(){if(!aimNode)return;aimNode.replaceChildren();if(!state.aim||!state.selected)return;let{x,y}=state.aim;aimNode.append(el('circle',{cx:x,cy:y,r:5}),el('path',{d:`M${x-12},${y}H${x-6}M${x+6},${y}H${x+12}M${x},${y-12}V${y-6}M${x},${y+6}V${y+12}`}));}
function point(cx,cy){return new DOMPoint(cx,cy).matrixTransform(world.getScreenCTM().inverse());}
function local(cx,cy){const r=$('mapStage').getBoundingClientRect();return{x:cx-r.left,y:cy-r.top};}
function hit(cx,cy){const e=document.elementsFromPoint(cx,cy).find(e=>e.classList?.contains('land'));return e?.dataset.id||null;}
function boardContains(cx,cy){let r=$('mapStage').getBoundingClientRect();return cx>=r.left&&cx<=r.right&&cy>=r.top&&cy<=r.bottom;}
function showGhost(cx,cy){ghost.replaceChildren();if(!state.selected||!boardContains(cx,cy))return;const p=byId.get(state.selected),q=point(cx,cy),parts=p.parts.filter(s=>layout.has(s.region));if(!parts.length)return;
 const under=document.elementsFromPoint(cx,cy).find(e=>e.dataset?.region)?.dataset.region;const a=parts.find(s=>s.region===under)||parts[0],l=layout.get(a.region),dx=q.x-(l.x+a.anchor[0]*l.s),dy=q.y-(l.y+a.anchor[1]*l.s);ghost.setAttribute('transform',`translate(${dx} ${dy})`);
 for(const part of parts){const e=mapPath(p,part,'');e.setAttribute('fill',p.color);e.removeAttribute('data-id');e.removeAttribute('data-region');ghost.append(e);}state.aim=local(cx,cy);drawAim();}
function placeAt(cx,cy){ghost.replaceChildren();if(!state.started){say('先に「ゲーム開始」を押してください。');return false;}if(state.done||state.preview||!state.selected)return false;const id=state.selected,found=hit(cx,cy);if(found!==id){say('↩ まだ違う場所です。ピースは置き場に戻りました。拡大して、輪郭を見比べてみましょう。','error');state.aim=null;drawAim();return false;}
 if(state.placed.has(id))return false;state.placed.add(id);const name=byId.get(id).name;clearSelection();update();say(`✓ ${name}、正解！${state.placed.size} / 41 ピースを配置しました。`,'success');if(state.placed.size===41)finish();return true;}
function update(){ $('count').textContent=state.placed.size;$('listCount').textContent=`${state.placed.size} / 41`;paintMap();renderTray();const list=$('placedNames');list.replaceChildren();for(const p of pieces){if(!state.placed.has(p.pieceId)&&!state.preview)continue;const b=document.createElement('button');b.textContent=`${p.number}. ${p.name}`;b.onclick=()=>focusRegion(p.parts[0].region);list.append(b);}}
function setView(view){cancelGesture();state.view=view;state.zoom=1;state.pan={x:0,y:0};state.aim=null;$('views').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));$('region').value='';$('mapCaption').textContent={all:'本島と離島を、ひとつずつ。',main:'沖縄本島 · 付属島も同じ自治体のピース',islands:'離島を大きく · 各枠は別縮尺'}[view];drawMap();renderTray();}
function zoomAt(f,x=width/2,y=height/2){const z=Math.max(.7,Math.min(18,state.zoom*f)),ratio=z/state.zoom;state.pan={x:x-(x-state.pan.x)*ratio,y:y-(y-state.pan.y)*ratio};state.zoom=z;transform();}
function fit(){state.zoom=1;state.pan={x:0,y:0};state.aim=null;$('region').value='';transform();}
function focusRegion(id){if(id==='south'){setView('main');const l=layout.get('main'),r=D.regions[0],lat=26.21,lon=127.74;let px=l.x+(lon-r.origin[0])*r.cos*1000*l.s,py=l.y+(r.origin[1]-lat)*1000*l.s;state.zoom=3.2;state.pan={x:width/2-px*3.2,y:height/2-py*3.2};transform();$('region').value='south';return;}if(!visibleRegion(id))setView(id==='main'?'main':'islands');const l=layout.get(id),r=D.regions.find(r=>r.id===id);if(!l)return;const cx=l.x+r.width*l.s/2,cy=l.y+r.height*l.s/2;state.zoom=Math.min(18,Math.min((width-65)/(r.width*l.s),(height-95)/(r.height*l.s)));state.pan={x:width/2-cx*state.zoom,y:height/2-cy*state.zoom};transform();$('region').value=id;}
function cancelGesture(){drag=null;dragPosition=null;pan=null;pinch=null;pointers.clear();document.body.classList.remove('dragging');ghost?.replaceChildren();}
// Carry a piece between the vertically stacked mobile tray and map.
window.addEventListener('pointermove',e=>{if(drag)dragPosition={x:e.clientX,y:e.clientY};});
function autoScroll(){if(drag?.moved&&dragPosition&&innerWidth<=740){let dy=dragPosition.y<65?-13:dragPosition.y>innerHeight-65?13:0;if(dy){window.scrollBy(0,dy);showGhost(dragPosition.x,dragPosition.y);}}requestAnimationFrame(autoScroll);}requestAnimationFrame(autoScroll);
window.addEventListener('pointermove',e=>{if(drag&&e.pointerId===drag.pointerId){if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>6)drag.moved=true;if(drag.moved){document.body.classList.add('dragging');showGhost(e.clientX,e.clientY);}return;}if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){let a=[...pointers.values()],dist=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),mid=local((a[0].x+a[1].x)/2,(a[0].y+a[1].y)/2);if(pinch){zoomAt(dist/pinch.dist,pinch.mid.x,pinch.mid.y);state.pan.x+=mid.x-pinch.mid.x;state.pan.y+=mid.y-pinch.mid.y;transform();}pinch={dist,mid};if(pan)pan.moved=true;return;}if(pan&&pointers.size===1){let dx=e.clientX-pan.x,dy=e.clientY-pan.y;if(Math.hypot(dx,dy)>5)pan.moved=true;if(pan.moved){state.pan={x:pan.origin.x+dx,y:pan.origin.y+dy};transform();}}});
window.addEventListener('pointerup',e=>{if(drag&&e.pointerId===drag.pointerId){const moved=drag.moved;drag=null;dragPosition=null;suppressClick=moved;setTimeout(()=>{suppressClick=false;},0);document.body.classList.remove('dragging');if(moved){if(boardContains(e.clientX,e.clientY))placeAt(e.clientX,e.clientY);else{ghost.replaceChildren();state.aim=null;drawAim();say('↩ ピースを置き場に戻しました。');}}return;}if(pointers.has(e.pointerId)){const tap=pan&&!pan.moved&&!pinch&&pointers.size===1;pointers.delete(e.pointerId);if(tap&&state.selected)placeAt(e.clientX,e.clientY);if(pointers.size===0){pan=null;pinch=null;}else{const p=[...pointers.values()][0];pan={x:p.x,y:p.y,origin:{...state.pan},moved:true};pinch=null;}}});
window.addEventListener('pointercancel',()=>{cancelGesture();state.aim=null;drawAim();});window.addEventListener('blur',()=>cancelGesture());
$('mapStage').addEventListener('pointerdown',e=>{if(e.target.closest('button')||e.button!==0)return;lastPointerType=e.pointerType;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});$('mapStage').setPointerCapture(e.pointerId);pan={x:e.clientX,y:e.clientY,origin:{...state.pan},moved:false};if(pointers.size===2){const a=[...pointers.values()];pinch={dist:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),mid:local((a[0].x+a[1].x)/2,(a[0].y+a[1].y)/2)};}e.preventDefault();});
$('mapStage').addEventListener('wheel',e=>{e.preventDefault();cancelGesture();const q=local(e.clientX,e.clientY);zoomAt(Math.exp(-e.deltaY*.002),q.x,q.y);},{passive:false});
$('mapStage').addEventListener('keydown',e=>{if(e.target!==$('mapStage'))return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const step=e.shiftKey?2:12;if(state.selected){state.aim ||= {x:width/2,y:height/2};state.aim.x=Math.max(0,Math.min(width,state.aim.x+(e.key==='ArrowRight'?step:e.key==='ArrowLeft'?-step:0)));state.aim.y=Math.max(0,Math.min(height,state.aim.y+(e.key==='ArrowDown'?step:e.key==='ArrowUp'?-step:0)));drawAim();}else{state.pan.x+=e.key==='ArrowLeft'?20:e.key==='ArrowRight'?-20:0;state.pan.y+=e.key==='ArrowUp'?20:e.key==='ArrowDown'?-20:0;transform();}}else if(e.key==='Enter'&&state.aim){e.preventDefault();let r=$('mapStage').getBoundingClientRect();placeAt(r.left+state.aim.x,r.top+state.aim.y);}else if(e.key==='Escape')clearSelection();else if(e.key==='+'||e.key==='='){e.preventDefault();zoomAt(1.3);}else if(e.key==='-'){e.preventDefault();zoomAt(1/1.3);}else if(e.key==='Home'){e.preventDefault();fit();}});
function start(){state.started=true;state.startTime=performance.now();state.elapsed=0;state.order.sort(()=>Math.random()-.5);$('start').textContent='↻ やり直す';$('phase').textContent=state.mode==='names'?'名前をたよりに、形を見つけよう':'ヒントを読んで、地図を考えよう';$('modes').querySelectorAll('button').forEach(b=>b.disabled=true);renderTray();say('ピースを選んで、地図の輪郭へ運びましょう。');}
function reset(){cancelGesture();state.started=false;state.done=false;state.preview=false;state.placed.clear();state.elapsed=0;clearSelection();$('start').textContent='▶ ゲーム開始';$('timer').textContent='00:00';$('phase').textContent='モードを選んで、はじめよう';$('modes').querySelectorAll('button').forEach(b=>b.disabled=false);$('previewBanner').hidden=true;$('answer').setAttribute('aria-pressed','false');$('answer').textContent='▧ 完成図を見る';$('hintName').textContent='どの形から、はじめる？';$('hintBasic').textContent='ピースを選ぶと、地理のヒントを表示します。';$('hintDetail').hidden=true;$('hintToggle').setAttribute('aria-expanded','false');$('linkedNote').textContent='';fit();update();say('モードを選び、「ゲーム開始」を押してください。');}
function finish(){tick();state.done=true;paintMap();$('phase').textContent='✓ 全41市町村を配置しました';$('finishTime').textContent=time(state.elapsed);$('placedList').open=true;$('completeDialog').showModal();}
function toggleAnswer(){cancelGesture();clearSelection();state.preview=!state.preview;$('previewBanner').hidden=!state.preview;$('answer').setAttribute('aria-pressed',String(state.preview));$('answer').textContent=state.preview?'▧ ゲームに戻る':'▧ 完成図を見る';update();say(state.preview?'完成図を表示中です。配置数は変わりません。経過時間は進みます。':'ゲームに戻りました。');}
$('start').onclick=()=>state.started?$('resetDialog').showModal():start();$('confirmReset').onclick=()=>{$('resetDialog').close();reset();};$('cancelReset').onclick=()=>$('resetDialog').close();$('again').onclick=()=>{$('completeDialog').close();reset();};$('review').onclick=()=>$('completeDialog').close();$('answer').onclick=toggleAnswer;$('closeAnswer').onclick=toggleAnswer;
$('modes').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(state.started)return;state.mode=b.dataset.mode;$('modes').querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderTray();});
$('views').querySelectorAll('button').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('zoomIn').onclick=()=>zoomAt(1.4);$('zoomOut').onclick=()=>zoomAt(1/1.4);$('fit').onclick=fit;$('filter').onchange=renderTray;$('clearSelection').onclick=clearSelection;
$('hintToggle').onclick=()=>{if(!state.selected&&!state.placed.size)return;if(!$('detailText').textContent)return;let open=$('hintDetail').hidden;$('hintDetail').hidden=!open;$('hintToggle').setAttribute('aria-expanded',String(open));$('hintMore').textContent=open?'詳しいヒントを閉じる ▴':'産物・歴史のヒントを開く ▾';};
$('helpBtn').onclick=()=>$('helpDialog').showModal();$('sourcesBtn').onclick=()=>$('sourcesDialog').showModal();$('locatorBtn').onclick=()=>{drawLocator();$('locatorDialog').showModal();};document.querySelectorAll('.dialog-close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('quickHint').onclick=()=>$('quickDialog').showModal();$('quickClose').onclick=()=>$('quickDialog').close();
$('expand').onclick=()=>{document.body.classList.toggle('map-stage-large');$('expand').setAttribute('aria-label',document.body.classList.contains('map-stage-large')?'通常の作業領域に戻す':'作業領域を広げる');};
for(const [id,name]of [['south','沖縄本島・南部'],...D.regions.map(r=>[r.id,r.name])]){let o=document.createElement('option');o.value=id;o.textContent=name;$('region').append(o);}$('region').onchange=()=>{$('region').value?focusRegion($('region').value):fit();};
function drawLocator(){const s=$('locator');s.replaceChildren();const minLon=122.7,maxLat=28.3,scale=78,cos=Math.cos(26*Math.PI/180),xy=(lon,lat)=>[45+(lon-minLon)*cos*scale,35+(maxLat-lat)*scale];for(const r of D.regions){const [x,y]=xy(r.origin[0],r.origin[1]);for(const p of D.pieces)for(const part of p.parts)if(part.region===r.id)s.append(el('path',{d:part.d,fill:'#88bdb2',stroke:'#4c8686','stroke-width':.5,'vector-effect':'non-scaling-stroke',transform:`translate(${x} ${y}) scale(${cos*scale/(r.cos*1000)} ${scale/1000})`}));const mid=xy((r.geo[0]+r.geo[2])/2,(r.geo[1]+r.geo[3])/2);let dy=r.id==='okidaito'?25:r.id==='kerama'?28:r.id==='west'?-17:r.id==='north'?-20:15;s.append(el('line',{x1:mid[0],y1:mid[1],x2:mid[0],y2:mid[1]+dy,stroke:'#769496','stroke-dasharray':'3 3'}),el('text',{x:mid[0],y:mid[1]+dy+10,'text-anchor':'middle',fill:'#244c57','font-size':10},r.name));}s.append(el('text',{x:740,y:35,'font-size':17,fill:'#244c57'},'N ↑'));}
let resizeTimer;new ResizeObserver(()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{cancelGesture();state.zoom=1;state.pan={x:0,y:0};state.aim=null;drawMap();},120);}).observe($('mapStage'));
drawMap();renderTray();
})();
